### ISSUE TITLE
확인된 버그들

### ISSUE THREAD

**Issue by Aqusiz** [swsnu/swpp2021-team12#47]
1. meeting/create로 연결해도 meeting/:id로 가버림 (App.js 라우팅 문제로 예상)
2. app.js에서 route 순서를 바꿔서 meeting/create로 주소창에 url을 직접 입력해 접속하면 들어가자마자 pageTemplate가 sign in page로 튕겨버림

**Comment by Aqusiz** [comment]
3. 새로고침시 로그아웃 되는 현상

**Comment by KylusheL** [comment]
1. meeting/create는 App.js에 추가해야 될 것 같네요.
